import type { ProductInput } from "@/types/product";

export function buildHotProductAnalysisSystemPrompt(): string {
  return [
    "你是 TEMU AI 图文生成前置报告助手。",
    "你的任务不是做最终上架判断，也不是做利润判断，而是根据商品信息生成产品包装方向、组合建议、1688 素材准备清单、ChatGPT 生图资料包和标题卖点资料包。",
    "TEMU 是强比价平台，不建议直接复制同款；只改标题、图片或描述，仍然可能存在较高比价风险。",
    "报告必须服务于后续 AI 图文生成：要说明产品结构、组合空间、配件关系、主图方向、标题卖点和素材准备。",
    "必须使用简体中文输出。JSON key 保持英文，JSON value 尽量使用中文。",
    "只返回 JSON，不要 Markdown，不要解释文字，不要代码块，不要 ```json。",
    "缺失信息写 unknown 或空数组，不得编造销量、评分、评论、认证、材质、承重、尺寸、成本、利润。",
    "不得使用保证、一定、百分百、必然、必爆、必过、绝对等绝对承诺。请使用可能、有助于、相对降低、建议测试、需要进一步验证等谨慎表达。",
    "preGenerationReport 是本次最重要的输出。推荐组合方案只能输出 planA 和 planB 两个方案，不要输出第三个组合方案。",
    "planA 必须是优先测试方案，planB 必须是备选升级方案。priorityAdvice 固定输出：建议优先执行方案 A。",
    "materialChecklist 用于 1688 素材准备，只输出主产品图、配件图、产品细节图、规格/尺码图、包装/重量信息截图、颜色/款式图；不要默认输出场景参考图或竞品图。",
    "imageGenerationPackage.copyText 必须是一段可直接复制给 ChatGPT 的中文资料包文本。",
    "titleSellingPointPackage.copyText 必须是一段可直接复制给 ChatGPT 的中文标题卖点资料包文本。",
    "boundaryReminder 固定表达：本报告只提供产品包装方向、组合建议、素材准备和 AI 图文生成资料，不代表最终上架建议。供货能力、真实成本、物流费用和利润结果，请卖家自行确认。",
    "为了兼容现有系统，也要保留 imageRecognition、hotProductAnalysis、directCopyRisk、recommendations、finalConclusion、actionSuggestions 字段；但 recommendations 最多 2 条即可，不要超过 2 条。"
  ].join("\n");
}

export function buildHotProductAnalysisUserPrompt(product: ProductInput): string {
  const productJson = JSON.stringify(
    {
      title: product.title,
      rawRecognizedTitle: product.rawRecognizedTitle ?? "unknown",
      cleanedProductName: product.cleanedProductName ?? "unknown",
      category: product.category,
      price: product.price,
      priceDisplay: product.priceDisplay ?? "unknown",
      priceCurrency: product.priceCurrency ?? "unknown",
      priceSource: product.priceSource ?? "unknown",
      priceCandidates: product.priceCandidates ?? [],
      weeklySales: product.weeklySales ?? "unknown",
      monthlySales: product.monthlySales ?? "unknown",
      rating: product.rating ?? "unknown",
      reviewsText: product.reviewsText?.trim() || "unknown",
      imageFileName: product.imageFileName ?? "unknown",
      imageCount: product.images?.length ?? (product.imageFileName ? 1 : 0),
      productSpecs: product.productSpecs ?? "unknown"
    },
    null,
    2
  );

  return [
    "请基于以下商品信息，生成 TEMU AI 图文生成前置报告 JSON。",
    "用户上传的图片越完整，越能判断产品结构、组合空间、配件关系、主图方向和标题卖点；如果图片不足，请在报告中谨慎表达。",
    "商品信息：",
    productJson,
    "",
    "请严格返回以下 JSON 结构：",
    "{",
    '  "preGenerationReport": {',
    '    "productBasics": {',
    '      "rawRecognizedTitle": "原始识别标题，尽量完整保留图片/截图中识别到的完整标题",',
    '      "productName": "产品名称",',
    '      "productCategory": "产品类目",',
    '      "currentComposition": "当前产品组成",',
    '      "mainUse": "产品主要用途",',
    '      "targetUsers": "适合人群",',
    '      "usageScenes": "主要使用场景"',
    "    },",
    '    "packagingValue": {',
    '      "worthPackaging": "值得 | 待观察 | 不建议",',
    '      "productType": "标品 | 半标品 | 非标品 | 混合型",',
    '      "priceComparisonRisk": "低 | 中 | 高",',
    '      "transformationSpace": "低 | 中 | 高",',
    '      "imageExpressionSpace": "低 | 中 | 高",',
    '      "skuDependency": "强依赖 | 中等依赖 | 弱依赖 | 不适用",',
    '      "currentSkuInfo": "当前 SKU 信息：已识别内容或未提供",',
    '      "skuConversionImpact": "高 | 中 | 低 | 不适用",',
    '      "skuSuggestion": "是否需要补充颜色、尺码、规格、容量、型号等信息",',
    '      "oneSentenceJudgment": "一句话判断"',
    "    },",
    '    "planA": {',
    '      "combinationName": "组合名称",',
    '      "combinationContent": "组合内容",',
    '      "targetUsers": "目标人群",',
    '      "usageScene": "使用场景",',
    '      "coreSellingPoints": "核心卖点",',
    '      "whyPriorityTest": "为什么适合优先测试",',
    '      "suitableImageTypes": "适合生成什么类型图片"',
    "    },",
    '    "planB": {',
    '      "combinationName": "组合名称",',
    '      "combinationContent": "组合内容",',
    '      "targetUsers": "目标人群",',
    '      "usageScene": "使用场景",',
    '      "coreSellingPoints": "核心卖点",',
    '      "whenToTry": "适合什么时候尝试",',
    '      "notes": "需要注意什么"',
    "    },",
    '    "materialChecklist": [',
    '      { "materialType": "主产品图", "requirement": "必须 | 建议 | 可选", "usage": "用途" }',
    "    ],",
    '    "imageGenerationPackage": {',
    '      "productName": "产品名称",',
    '      "productCategory": "产品类目",',
    '      "recommendedCombinationPlan": "推荐组合方案",',
    '      "combinationContent": "组合内容",',
    '      "targetUsers": "目标人群",',
    '      "usageScene": "使用场景",',
    '      "coreSellingPoints": "核心卖点",',
    '      "referenceImages": "已上传",',
    '      "imageCount": "5 张",',
    '      "imageRatio": "1:1 正方形",',
    '      "imageStyle": "干净、清晰、有电商销售感，适合 TEMU 平台",',
    '      "specInfo": "规格信息：主产品规格、配件规格、产品尺寸、包装重量、包装尺寸、颜色/尺码选项；如果有规格信息，请生成一张规格/尺码说明图；如果规格信息不完整，不要编造尺寸、重量、材质、承重或认证数据。",',
    '      "restrictions": "不要出现品牌词，不要夸大功能，不要改变产品主体结构，不要生成产品没有的功能",',
    '      "copyText": "可复制给 ChatGPT 的完整中文资料包文本"',
    "    },",
    '    "titleSellingPointPackage": {',
    '      "productName": "产品名称",',
    '      "productCategory": "产品类目",',
    '      "combinationPlan": "组合方案",',
    '      "productImages": "已上传",',
    '      "targetPlatform": "TEMU",',
    '      "outputRequirements": ["3 个 TEMU 商品标题", "推荐使用的标题", "5 个核心卖点", "5 张图对应短文案", "详情页简短描述"],',
    '      "fixedRequirements": ["不要出现品牌词", "不要出现未经确认的认证、材质、承重、尺寸、数据", "不要夸大产品功能", "不要写虚假效果", "标题要简洁、清楚，适合电商平台", "如果是组合产品，要突出组合价值和使用场景"],',
    '      "copyText": "可复制给 ChatGPT 的完整中文标题卖点资料包文本"',
    "    },",
    '    "boundaryReminder": "本报告只提供产品包装方向、组合建议、素材准备和 AI 图文生成资料，不代表最终上架建议。供货能力、真实成本、物流费用和利润结果，请卖家自行确认。"',
    "  },",
    '  "imageRecognition": { "productType": "string", "category": "string", "mainColors": [], "secondaryColors": [], "styleDescription": "string", "productStructure": "single | bundle | multi_pack | unknown", "standardizationLevel": "standard | semi_standard | non_standard | unknown", "visibleAccessories": [], "usageScenes": [], "targetUsers": [], "imageStyle": "string", "clickPotentialFactors": [], "sellingPointElements": [], "unknownFields": [] },',
    '  "hotProductAnalysis": { "hotProductType": "price | color | style | image_click_rate | comprehensive | unknown", "possibleWinningFactors": [], "unknownFactors": [], "confidence": "low | medium | high | unknown", "notes": [] },',
    '  "directCopyRisk": { "riskLevel": "low | medium | high | unknown", "riskScore": 0, "reasons": [], "riskWarnings": [], "riskReductionSuggestions": [] },',
    '  "recommendations": [],',
    '  "finalConclusion": "中文运营建议",',
    '  "actionSuggestions": []',
    "}",
    "",
    "硬性要求：",
    "- preGenerationReport.planA 和 preGenerationReport.planB 只能是两个方案。",
    "- 不要让报告承担真实利润判断，不要给出最终上架结论。",
    "- 不要教供应链，只列素材准备清单和图文生成资料。",
    "- SKU 判断必须先看产品类目：狗背带、服装、鞋帽、饰品、宠物穿戴类通常强依赖颜色/尺码/规格；部分收纳、杯具、配件类可能中等依赖容量/型号/规格；天生单规格产品不要因为缺少颜色或尺码就判断为缺陷。",
    "- 如果图片识别到颜色/尺码/规格，可作为 currentSkuInfo；识别不到时不要默认扣分，要结合品类判断 skuDependency 和 skuConversionImpact。",
    "- productBasics.rawRecognizedTitle 用于溯源，允许保留品牌词；productBasics.productName、生图资料包和标题卖点资料包必须使用清洗后的通用产品名称，不要使用品牌词。",
    "- copyText 字段必须包含完整可复制文本，不要只写一句说明。生图资料包必须包含规格信息字段：主产品规格、配件规格、产品尺寸、包装重量、包装尺寸、颜色/尺码选项。",
    "- 所有字符串值必须是中文，商品原始英文标题可以在产品名称中保留。"
  ].join("\n");
}
