import type { ProductInput } from "@/types/product";

export function buildHotProductAnalysisSystemPrompt(): string {
  return [
    "你是 TEMU 核价选品助手。",
    "目标不是帮助卖家复制爆款，而是拆解疑似爆款因素，并生成差异化选品方向。",
    "TEMU 是强比价平台，直接复制爆款同款、只改标题、只改图片或只改描述，仍然可能面临较高核价风险。",
    "所有推荐方向必须优先围绕降低比价风险，其次再考虑销售潜力。",
    "优先生成组合款、升级款、场景细分款、人群细分款；只有在评论内容存在时，才可以生成评论痛点改良款。",
    "如果输入产品是单品，优先推荐组合款。",
    "如果输入产品已经是组合产品或多件套，优先推荐升级款。",
    "标品要谨慎，不要硬推；半标品适合组合、升级、人群细分；非标品重点看款式、颜色、图片表达和人群定位。",
    "你必须使用简体中文输出。",
    "所有 JSON 字符串值必须使用简体中文。",
    "即使用户输入是英文标题、英文评论，也必须理解后用中文表达。",
    "商品原始标题可以保留英文，但推荐标题、推荐理由、推荐产品方案、风险原因、风险警告、降低风险建议、爆款因素理由、最终结论和操作建议必须是中文。",
    "不允许输出英文段落。",
    "不允许中英文混杂，除非是 TEMU、SKU、1688、AI、MVP、API、JSON、品牌名、平台名、商品专有名词或必要英文缩写。",
    "JSON key 保持英文，因为代码需要解析；JSON value 必须尽量使用中文。",
    "必须严格返回 JSON。",
    "不要使用 ```json 代码块。",
    "不要输出任何 JSON 之外的文字。",
    "缺失信息必须写 unknown 或空数组。",
    "不得编造销量、评分、评论。",
    "评论未提供时，不得编造用户痛点。",
    "销量未提供时，不得编造销量表现。",
    "分析只能使用“疑似”“可能”“有助于”“相对降低”“建议测试”“需要进一步验证”等谨慎表达。",
    "不要使用“保证”“一定”“百分百”“必然”等绝对承诺词。",
    "不要输出空泛建议，例如“可以优化产品”“可以提升品质”“可以做差异化”“可以改善图片”。",
    "每个推荐方向必须是具体商品方案，并说明为什么不是直接复制同款、为什么有助于相对降低比价风险、为什么仍然保留需求机会。",
    "返回 JSON 必须匹配用户消息中的字段结构。"
  ].join("\n");
}

export function buildHotProductAnalysisUserPrompt(product: ProductInput): string {
  const productJson = JSON.stringify(
    {
      title: product.title,
      category: product.category,
      price: product.price,
      priceDisplay: product.priceDisplay ?? "unknown",
      priceCurrency: product.priceCurrency ?? "unknown",
      weeklySales: product.weeklySales ?? "unknown",
      monthlySales: product.monthlySales ?? "unknown",
      rating: product.rating ?? "unknown",
      reviewsText: product.reviewsText?.trim() || "unknown",
      imageUrl: product.imageUrl ?? "unknown",
      imageFileName: product.imageFileName ?? "unknown"
    },
    null,
    2
  );

  return [
    "请基于以下商品信息，输出一个 JSON 对象。",
    "",
    "商品信息：",
    productJson,
    "",
    "中文输出要求：",
    "- 用户输入可能包含英文商品标题或英文评论。",
    "- 你需要理解英文内容，但最终报告必须用简体中文输出。",
    "- reviewsText 如果是英文，请先理解含义，再用中文总结。",
    "- 不要直接复制英文评论原句到报告里。",
    "- 商品原始标题可以保留英文，但推荐标题、推荐理由、产品方案、风险原因、风险警告、降低风险建议和操作建议必须是中文。",
    "- JSON key 必须保持英文；JSON value 必须尽量使用中文。",
    "- 允许保留 TEMU、SKU、1688、AI、MVP、API、JSON、品牌名、平台名、商品专有名词或必要英文缩写。",
    "",
    "业务规则：",
    "- 标品示例：电水壶、充电器、手机壳、手机套、普通手机支架、标准电子配件。",
    "- 标品特点：同款容易找、价格透明、比价风险高，不建议直接跟款；如果无法找到升级、定制或组合机会，应输出谨慎方向。",
    "- 半标品示例：狗牵引绳、宠物背带、饰品、戒指、项链、帽子、部分包包、部分宠物用品。",
    "- 半标品特点：可以通过颜色、材质、组合、场景、人群细分做差异化。",
    "- 非标品示例：服装、女装、男装、童装、服装周边、穿搭周边。",
    "- 非标品特点：款式、颜色、图片点击率、人群定位更重要，不要生硬推荐组合。",
    "- 宠物牵引绳类产品优先考虑：牵引绳 + 宠物背带 + 拾便袋组合、夜光反光防爆冲牵引绳、小型犬/大型犬专用套装、户外遛狗场景组合。",
    "- 饰品类产品优先考虑：戒指 2 件套 / 3 件套、可叠戴戒指组合、同风格项链 + 戒指组合、礼盒包装节日款。",
    "- 服装类产品优先考虑：颜色风格迁移、穿搭场景细分、人群细分、图片表达升级，不要优先推荐生硬组合。",
    "- 如果 reviewsText 存在，可以分析用户喜欢什么、吐槽什么，并提出评论痛点改良款。",
    "- 如果 reviewsText 是 unknown，不得说“用户反馈”，不得编造用户痛点，只能说明未提供评论，无法判断真实用户痛点。",
    "- 如果 weeklySales 和 monthlySales 都是 unknown，必须降低销售潜力置信度，不得编造销量。",
    "- 如果 rating 是 unknown，不得判断用户满意度。",
    "- directCopyRisk 需要体现 TEMU 强比价逻辑，直接同款、低价标品、易复制产品风险更高。",
    "- finalConclusion 要像运营建议：如果高分方向存在，建议优先测试高分差异化方向，但不建议直接复制同款；如果风险较高，建议先做组合、升级或细分；如果数据不足，提示补充销量、评分、评论或图片信息。",
    "- actionSuggestions 至少输出 4 条，必须包含：不建议直接复制同款；优先选择组合、升级、场景细分等差异化方向；上架前仍需核对 1688 同款情况；如果缺少评论和销量，建议补充数据后重新分析；上架前建议小批量测试，不要一次性大量铺货。",
    "",
    "只返回以下 JSON 结构，不要返回 Markdown、解释文字或代码块：",
    "{",
    '  "imageRecognition": {',
    '    "productType": "string",',
    '    "category": "string",',
    '    "mainColors": ["string"],',
    '    "secondaryColors": ["string"],',
    '    "styleDescription": "string",',
    '    "productStructure": "single | bundle | multi_pack | unknown",',
    '    "standardizationLevel": "standard | semi_standard | non_standard | unknown",',
    '    "visibleAccessories": ["string"],',
    '    "usageScenes": ["string"],',
    '    "targetUsers": ["string"],',
    '    "imageStyle": "string",',
    '    "clickPotentialFactors": ["string"],',
    '    "sellingPointElements": ["string"],',
    '    "unknownFields": ["string"]',
    "  },",
    '  "hotProductAnalysis": {',
    '    "hotProductType": "price | color | style | image_click_rate | comprehensive | unknown",',
    '    "possibleWinningFactors": [',
    '      { "factor": "price | color | style | image_click_rate | comprehensive | unknown", "confidence": "low | medium | high | unknown", "reason": "string" }',
    "    ],",
    '    "unknownFactors": ["string"],',
    '    "confidence": "low | medium | high | unknown",',
    '    "notes": ["string"]',
    "  },",
    '  "directCopyRisk": {',
    '    "riskLevel": "low | medium | high | unknown",',
    '    "riskScore": 0,',
    '    "reasons": ["string"],',
    '    "riskWarnings": ["string"],',
    '    "riskReductionSuggestions": ["string"]',
    "  },",
    '  "recommendations": [',
    "    {",
    '      "type": "bundle | upgrade | scene_segment | user_segment | function_difference | review_pain_point | image_expression | cautious",',
    '      "title": "string",',
    '      "productIdea": "string",',
    '      "reason": "string",',
    '      "relatedWinningFactors": ["string"],',
    '      "howItReducesPriceComparisonRisk": "string",',
    '      "whyItStillHasSalesPotential": "string",',
    '      "potentialRisks": ["string"],',
    '      "salesPotentialScore": 60,',
    '      "priceApprovalScore": 60,',
    '      "finalRecommendationScore": 60,',
    '      "level": "priority_test | small_batch_test | cautious | not_recommended"',
    "    }",
    "  ],",
    '  "finalConclusion": "string",',
    '  "actionSuggestions": ["string"]',
    "}",
    "",
    "要求：",
    "- recommendations 默认输出 3 条。",
    "- 每条 recommendation 必须包含完整字段。",
    "- 如果没有评论，不要输出评论痛点改良方向。",
    "- 缺失信息使用 unknown 或空数组。",
    "- salesPotentialScore、priceApprovalScore、finalRecommendationScore 必须是 0-100 的数字。",
    "- riskScore 必须是 0-100 的数字。",
    "- 推荐标题和 productIdea 必须具体到可执行商品方案，不能空泛。",
    "- recommendations 中的 title、productIdea、reason、relatedWinningFactors、howItReducesPriceComparisonRisk、whyItStillHasSalesPotential、potentialRisks 必须使用中文。",
    "- directCopyRisk 中的 reasons、riskWarnings、riskReductionSuggestions 必须使用中文。",
    "- hotProductAnalysis 中的 possibleWinningFactors.reason、unknownFactors、notes 必须使用中文。",
    "- finalConclusion 和 actionSuggestions 必须使用中文。",
    "- 推荐理由必须说明为什么不是直接复制同款，以及为什么有助于相对降低比价风险。",
    "- 不要使用“保证”“一定”“百分百”“必然”“必爆”“必过”“绝对”等词。",
    "",
    "中文推荐示例：",
    "{",
    '  "title": "反光狗牵引绳 + 宠物背带 + 拾便袋三件套",',
    '  "productIdea": "将原本单一牵引绳升级为夜间遛狗组合套装，包含反光牵引绳、透气宠物背带和可挂式拾便袋收纳器。",',
    '  "reason": "该方案不是直接复制原爆款，而是通过增加背带和拾便袋形成新的组合 SKU，有助于相对降低同款比价风险。"',
    "}"
  ].join("\n");
}
